version: '3.9'
services:
  botkit_service:
    build: 
      context: .
    container_name: "bot_container" 
    ports:
      - 3000:3000 
    volumes:
      - ./bot_vol/:/working_dir/bot_vol
      #- sql_volume:/working_dir/sqlite

#  sql_volume: